export const COLLAPSED_HEADER_HEIGHT = 64
export const EXPANDED_HEADER_HEIGHT = 300
export const HEADER_DELTA = EXPANDED_HEADER_HEIGHT - COLLAPSED_HEADER_HEIGHT
export const BUTTON_HEIGHT = 48
export const BUTTON_WIDTH = 200
